feat: add pair addr
oraichain/oraidex-sdk pull request #263
Opened 2024-05-06 02:53 UTC by quangdz1704

feat: add pair addr

2024-05-06 03:02 UTC, haunv3 approved these changes

2024-05-06 03:25 UTC, trungbach requested changes

2024-05-06 03:25 UTC, trungbach commented on packages/oraidex-common/src/pairs.ts
> +export enum PairAddress {
i think we can use Record with key get from list Pairs that was configured already so it can avoid missed pair when list Pairs add new

2024-05-08 08:40 UTC, trungbach approved these changes

2024-05-08 08:53 UTC, merged