Fix/fou 583
oraichain/oraidex-sdk pull request #71
Opened 2023-12-03 08:48 UTC by trungbach

2023-12-03 09:44 UTC, lehieuhust approved these changes

2023-12-03 09:51 UTC, haunv3 approved these changes

2023-12-05 04:50 UTC, ducphamle2 requested changes

2023-12-05 04:50 UTC, ducphamle2 commented on .env.example
> +FACTORY_CONTACT_ADDRESS_V1="orai1hemdkz4xx9kukgrunxu3yw0nvpyxf34v82d2c8"
I believe we can use the constants in oraidex-common instead

2023-12-05 04:50 UTC, ducphamle2 commented on packages/oraidex-sync/src/tx-parsing.ts
> +    const earnAmountInUsdt = rewardAssetPrice * earnAmounts[i] + oraiPrice * oraiEarnedAmount;
Should we move this to a seperate function with tests?

2023-12-06 08:30 UTC, haunv3 submitted a review, later dismissed

2023-12-06 08:49 UTC, binhtt01 approved these changes

2023-12-06 08:50 UTC, binhtt01 approved these changes

2023-12-07 06:58 UTC, lehieuhust approved these changes

2023-12-07 06:58 UTC, quangdz1704 approved these changes

2023-12-07 07:15 UTC, closed without merging